export const PermissionsRegistry = {
  USER: {
    CREATE: "USER.CREATE",
    READ: "USER.READ",
    UPDATE: "USER.UPDATE",
    DELETE: "USER.DELETE",
    ASSIGN_PERMISSIONS: "USER.ASSIGN_PERMISSIONS",
  },

  ROLE: {
    CREATE: "ROLE.CREATE",
    READ: "ROLE.READ",
    UPDATE: "ROLE.UPDATE",
    DELETE: "ROLE.DELETE",
    ASSIGN_PERMISSIONS: "ROLE.ASSIGN_PERMISSIONS",
  },

  PERMISSION: {
    READ: "PERMISSION.READ",
    ASSIGN: "PERMISSION.ASSIGN",
  },

  PLACE: {
    CREATE: "PLACE.CREATE",
    READ: "PLACE.READ",
    UPDATE: "PLACE.UPDATE",
    DELETE: "PLACE.DELETE",
  },

  SLOT: {
    CREATE: "SLOT.CREATE",
    READ: "SLOT.READ",
    UPDATE: "SLOT.UPDATE",
    DELETE: "SLOT.DELETE",
  },

  TICKET_TYPE: {
    CREATE: "TICKET_TYPE.CREATE",
    READ: "TICKET_TYPE.READ",
    UPDATE: "TICKET_TYPE.UPDATE",
    DELETE: "TICKET_TYPE.DELETE",
  },

  ADDON: {
    CREATE: "ADDON.CREATE",
    READ: "ADDON.READ",
    UPDATE: "ADDON.UPDATE",
    DELETE: "ADDON.DELETE",
  },

  BOOKING: {
    CREATE: "BOOKING.CREATE",
    READ: "BOOKING.READ",
    UPDATE: "BOOKING.UPDATE",
    DELETE: "BOOKING.DELETE",
    CANCEL: "BOOKING.CANCEL",
  },

  TICKET: {
    CREATE: "TICKET.CREATE",
    READ: "TICKET.READ",
    UPDATE: "TICKET.UPDATE",
    DELETE: "TICKET.DELETE",
    SCAN: "TICKET.SCAN",
  },

  SCAN_LOG: {
    READ: "SCAN_LOG.READ",
    CREATE: "SCAN_LOG.CREATE",
  },

  SETTING: {
    READ: "SETTING.READ",
    UPDATE: "SETTING.UPDATE",
  },

  DASHBOARD: {
    READ: "DASHBOARD.READ",
  },
};